[package]
name = "counter_canister_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.13.2"
ic-cdk-macros = "0.13.2"
serde = { version = "1.0", features = ["derive"] }
candid = "0.9"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
